### ISSUE TITLE
"Undefined" error on register form

### ISSUE THREAD

**Issue by victorcamposm** [bonino97/LemonBooster-v2#6]
Hi team,

I get an error when I try to register:
![image](https://user-images.githubusercontent.com/37191037/108695799-fec97f00-7500-11eb-8413-a0a64ae6fb5f.png)

Can you show a self-explained error message or tell me what can be happening?

**Comment by bonino97** [comment]
Try again @victorcamposm, DO put the API droplet on maintenance.

Regards.

**Comment by victorcamposm** [comment]
Fixed. Thanks!
